spring:
  profiles:
    active: local
    group:
      local: local, common, secret
      blue: blue, common, secret
      green: green, common, secret

server:
  env: blue

---

spring.config.activate.on-profile: local

server:
  port: 8094
  serverAddress: localhost

serverName: local_server

---

spring.config.activate.on-profile: blue

server:
  port: 8094
  serverAddress: 34.47.36.146

serverName: blue_server

---

spring.config.activate.on-profile: green

server:
  port: 8095
  serverAddress: 34.47.36.146

serverName: green_server

---

spring.config.activate.on-profile: common

spring.application.name: actions-test

