name: Blue-Green Deployment

on:
  push:
    branches:
      - test

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to GCP VM
      env:
        GCP_SSH_KEY: ${{ secrets.GCP_SSH_KEY }}
        VM_IP: ${{ secrets.GCP_VM_IP }}
        VM_USERNMAE: ${{ secrets.GCP_VM_USERNAME }}
      run: |
        mkdir -p ~/.ssh
        echo "$GCP_SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $VM_IP >> ~/.ssh/known_hosts
        ssh "$VM_USERNAME@$VM_IP" "echo 'SSH works!'"
